trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - script: docker login -u $(USERNAME) -p $(PASSWORD)
  - script: docker build -t $(USERNAME)/llm-service:$(Build.BuildId) .
  - script: docker push $(USERNAME)/llm-service:$(Build.BuildId)