trigger:
- master
- dev
- test

pool:
  vmImage: ubuntu-latest

variables:
  image_name: 'llm-service'
  repo_name: 'maaft'

steps:
  - script: |
      branch=$(Build.SourceBranchName)
      if [ "$branch" = "dev" ]; then
        echo "##vso[task.setvariable variable=tag]dev-$(Build.BuildId)"
      elif [ "$branch" = "test" ]; then
        echo "##vso[task.setvariable variable=tag]test-$(Build.BuildId)"
      else
        echo "##vso[task.setvariable variable=tag]prod-$(Build.BuildId)"
      fi
    displayName: Set Image Tags
  - task: Docker@2
    displayName: Build Image
    inputs:
      containerRegistry: ayodeji_docker
      command: build
      repository: $(repo_name)/$(image_name)
      Dockerfile: '**/Dockerfile'
      tags: $(tag)

  - task: Docker@2
    displayName: Push Image
    inputs:
      containerRegistry: ayodeji_docker
      command: push
      repository: $(repo_name)/$(image_name)
      tags: $(tag)