trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ayodeji_docker'
    command: 'login'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    command: 'push'